(function () {
  "use strict";
  const routes = [["Home","/",["/","/home"]],["Create","/create",["/create"]],["Tools","/plugins",["/plugins"]],["Workshop","/workshop",["/workshop"],"workshop-link"],["Model Lab","/model-lab",["/model-lab"],"model-lab-link"],["Setup","/configuration",["/configuration","/setup","/configuration/avatar"]],["System","/system-details",["/system-details","/details","/index.html"]]];
  function make(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
  function addRuntimeChip(root,label,value,id){const chip=make("span","ariadne-runtime-chip");chip.id=id;chip.append(make("span","chip-label",label),make("span","chip-value",value));root.append(chip);return chip}
  const bar=make("header","ariadne-appbar"),inner=make("div","ariadne-appbar-inner"),brand=make("a","ariadne-appbrand");brand.href="/";brand.setAttribute("aria-label","Ariadne Home");
  const brandCopy=make("span","ariadne-appbrand-copy");brandCopy.append(make("strong","","Ariadne"),make("small","","Local production system"));brand.append(make("span","ariadne-appbrand-mark","◈"),brandCopy);
  const nav=make("nav","ariadne-primary-nav");nav.setAttribute("aria-label","Primary Ariadne navigation");const currentPath=window.location.pathname;
  routes.forEach(([label,href,matches,extraClass])=>{const link=make("a",extraClass||"",label);link.href=href;if(matches.includes(currentPath)){link.classList.add("active");link.setAttribute("aria-current","page")}nav.append(link)});
  const commands=make("div","ariadne-command-area"),profileChip=addRuntimeChip(commands,"Environment","Checking","ariadne-profile-chip"),gpuChip=addRuntimeChip(commands,"GPU","Checking","ariadne-gpu-chip"),serviceChip=addRuntimeChip(commands,"Services","Checking","ariadne-service-chip");
  const modelWrap=make("div","ariadne-model-wrap"),modelTrigger=make("button","ariadne-model-trigger");modelTrigger.id="ariadne-model-trigger";modelTrigger.type="button";modelTrigger.setAttribute("aria-expanded","false");
  const triggerCopy=make("span","ariadne-model-trigger-copy");triggerCopy.append(make("small","","Active model"),make("strong","","Checking…"));modelTrigger.append(triggerCopy,make("span","ariadne-model-chevron","▾"));
  const panel=make("section","ariadne-model-panel");panel.hidden=true;panel.setAttribute("aria-label","Ariadne model selection");const panelHead=make("div","ariadne-model-panel-head"),heading=make("div");heading.append(make("span","","ARIADNE MODEL CONTROL"),make("strong","","Choose the working model"));const current=make("div","ariadne-model-current","Reading runtime…");panelHead.append(heading,current);
  const label=make("label","","Installed Ollama model"),select=make("select");select.id="ariadne-model-select";select.setAttribute("aria-label","Installed Ollama model");label.append(select);const meta=make("div","ariadne-model-meta"),residency=make("span","","Resident: checking"),provider=make("span","","Provider: local");meta.append(residency,provider);
  const actions=make("div","ariadne-model-actions"),status=make("span","ariadne-model-status","Select a model, then apply."),apply=make("button","ariadne-model-apply","Use this model");status.setAttribute("role","status");apply.type="button";actions.append(status,apply);panel.append(panelHead,label,meta,actions);modelWrap.append(modelTrigger,panel);commands.append(modelWrap);inner.append(brand,nav,commands);bar.append(inner);document.body.prepend(bar);document.body.classList.add("has-ariadne-shell");
  function setChip(chip,value,state){chip.querySelector(".chip-value").textContent=value;chip.classList.remove("attention","offline");if(state)chip.classList.add(state)}
  function bytes(value){const amount=Number(value||0);return amount?`${(amount/1024**3).toFixed(1)} GB`:"size unknown"}
  async function loadModelControl(){try{const response=await fetch("/api/model-control",{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.message||`HTTP ${response.status}`);const active=payload.active_model||"No model selected";triggerCopy.querySelector("strong").textContent=active;current.textContent=`${active} · ${payload.location||"desktop"}`;provider.textContent=`Provider: ${payload.provider_id||"unconfigured"}`;const loaded=Array.isArray(payload.loaded)?payload.loaded:[];residency.textContent=loaded.length?`Resident: ${loaded.join(", ")}`:"Resident: none";const selectedBefore=select.value;select.replaceChildren();(payload.models||[]).forEach(item=>select.add(new Option(`${item.name} · ${bytes(item.size)}`,item.name)));select.value=selectedBefore&&[...select.options].some(option=>option.value===selectedBefore)?selectedBefore:active;apply.disabled=!select.options.length;const homeModel=document.querySelector("#model-name");if(homeModel)homeModel.textContent=active}catch(error){triggerCopy.querySelector("strong").textContent="Model control unavailable";status.textContent=error.message;status.className="ariadne-model-status error";apply.disabled=true}}
  async function loadRuntime(){try{const response=await fetch("/api/status",{cache:"no-store"}),payload=await response.json(),deployment=payload.deployment?.display||payload.profile||"Unknown";setChip(profileChip,deployment,payload.deployment?.transition_state==="ready"?"":"attention");const owner=payload.gpu_owner?.current_gpu_owner||"NONE",free=payload.gpu?.available?`${payload.gpu.free_gb} GB free`:"telemetry pending";setChip(gpuChip,`${owner} · ${free}`,payload.gpu_owner?.transition_state==="IDLE"?"":"attention");const nativeState=String(payload.native_runtime?.state||"unknown").toLowerCase();setChip(serviceChip,nativeState==="ready"?"Native online":nativeState==="unknown"?"Checking":"Attention",nativeState==="ready"?"":nativeState==="unknown"?"attention":"offline");window.dispatchEvent(new CustomEvent("ariadne:runtime",{detail:payload}))}catch(_error){setChip(serviceChip,"Unavailable","offline")}}
  modelTrigger.addEventListener("click",()=>{panel.hidden=!panel.hidden;modelTrigger.setAttribute("aria-expanded",String(!panel.hidden))});document.addEventListener("click",event=>{if(!modelWrap.contains(event.target)){panel.hidden=true;modelTrigger.setAttribute("aria-expanded","false")}});
  apply.addEventListener("click",async()=>{const model=select.value;if(!model)return;apply.disabled=true;status.className="ariadne-model-status";status.textContent=`Ariadne is loading ${model}…`;try{const response=await fetch("/api/model-control/select",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({model})}),payload=await response.json();if(!response.ok||!payload.ok)throw new Error(payload.message||`HTTP ${response.status}`);status.className="ariadne-model-status success";status.textContent=payload.message;await Promise.all([loadModelControl(),loadRuntime()])}catch(error){status.className="ariadne-model-status error";status.textContent=error.message}finally{apply.disabled=!select.options.length}});
  loadModelControl();loadRuntime();window.setInterval(loadRuntime,10000);window.setInterval(loadModelControl,30000);
})();
